apiVersion: v1
kind: Service
# имя сервиса и лейбл
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
    # с каким подом работает сервис
  selector:
    app: ftps
  ports:
    - port: 20
      name: connection
    - port: 21 # порт в LoadBalancer
      name: transfer
    - port: 21100
      name: passive

---

apiVersion: apps/v1
kind: Deployment
# установка deploy-имени и лейбла
metadata:
  name: ftps
  labels:
    app: ftps
spec:
# с каким подом работает развертывание
  selector:
    matchLabels:
      app: ftps
  # перед созданием нового пода, старый будет удален
  strategy:
    type: Recreate
  replicas: 1
  # создание пода
  template:
    metadata:
      labels:
        app: ftps
    spec:
      # под базируется на контейнере
      containers:
        - name: ftps
          image: ftp_i:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 21100