apiVersion: v1
kind: Service
# имя сервиса и лейбл
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  # с каким подом работает сервис
  ports:
    - name: mysql
      port: 3306 # порт ClusterIP
  selector:
    app: mysql

---
# хранилище для mysql
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
# установка deploy-имени и лейбла
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  # с каким подом работает развертывание
  selector:
    matchLabels:
      app: mysql
  # перед созданием нового пода, старый будет удален
  strategy:
    type: Recreate
  replicas: 1
  # создание пода
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # под базируется на контейнере
      containers:
        - name: mysql
          image: mysql_i:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
              name: mysql
          # с каким томом работает контейнер
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql