apiVersion: v1
kind: Service
# имя сервиса и лейбл
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  # с каким подом работает сервис
  selector:
    app: nginx
  ports:
    - port: 80
      name: http
    - port: 443 # порт в LoadBalancer
      name: https
    - port: 22
      name: ssh

---

apiVersion: apps/v1
kind: Deployment
# установка deploy-имени и лейбла
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  # с каким подом работает развертывание
  selector:
    matchLabels:
      app: nginx
  # перед созданием нового пода, старый будет удален
  strategy:
    type: Recreate
  replicas: 1
  # создание пода
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # под базируется на контейнере
      containers:
        - name: nginx
          image: nginx_i:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
          livenessProbe:
            exec:
              command:
                - pidof
                - sshd
            initialDelaySeconds: 15
            periodSeconds: 3