apiVersion: v1
kind: Service
# имя сервиса и лейбл
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
      name: connection
---

apiVersion: apps/v1
kind: Deployment
# установка deploy-имени и лейбла
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  # перед созданием нового пода, старый будет удален
  strategy:
    type: Recreate
  replicas: 1
  # создание пода
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      # под базируется на контейнере
      containers:
        - name: phpmyadmin
          image: pma_i:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 3