apiVersion: v1
kind: Service
# имя сервиса и лейбл
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  # с каким подом работает сервис
  selector:
    app: wordpress
  ports:
    - port: 5050 # порт в LoadBalancer
      name: http
---

apiVersion: apps/v1
kind: Deployment
# установка deploy-имени и лейбла
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  # с каким подом работает развертывание
  selector:
    matchLabels:
      app: wordpress
  # перед созданием нового пода, старый будет удален
  strategy:
    type: Recreate
  replicas: 1
  # создание пода
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      # под базируется на контейнере
      containers:
        - name: wordpress
          image: wp_i:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          livenessProbe:
            httpGet:
              path: /
              port: 5050
            initialDelaySeconds: 15
            periodSeconds: 3
